<a href="https://colab.research.google.com/github/Hongyongmin/Edwith-Pytorch/blob/main/2_Linear_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import torch.optim as optim

In [ ]:
x_train = torch.FloatTensor([[1],[2],[3]]) ##입력데이터
y_train = torch.FloatTensor([[2],[4],[6]]) ##출력데이터

# Linear Regression은 하나의 직선을 찾는 일, W는 기울기(Weight) b 는 y절편(bias)

W = torch.zeros(1, requires_grad=True) #0으로 초기화 한뒤, 학습시킬것을 명시
b = torch.zeros(1, requires_grad=True)

optimizer = optim.SGD([W,b], lr=0.02)

nb_epochs = 1500
for epoch in range(1, nb_epochs + 1):
    hypothesis = x_train *W +b
    cost = torch.mean((hypothesis - y_train) **2) ## Coumpute lost를 구하는 과정
    print(W,b)
    
    optimizer.zero_grad() #미분값 초기화
    cost.backward() #역전파
    optimizer.step() # 파라미터 갱신

tensor([0.], requires_grad=True) tensor([0.], requires_grad=True)
tensor([0.3733], requires_grad=True) tensor([0.1600], requires_grad=True)
tensor([0.6642], requires_grad=True) tensor([0.2837], requires_grad=True)
tensor([0.8908], requires_grad=True) tensor([0.3792], requires_grad=True)
tensor([1.0675], requires_grad=True) tensor([0.4528], requires_grad=True)
tensor([1.2054], requires_grad=True) tensor([0.5093], requires_grad=True)
tensor([1.3130], requires_grad=True) tensor([0.5525], requires_grad=True)
tensor([1.3970], requires_grad=True) tensor([0.5854], requires_grad=True)
tensor([1.4627], requires_grad=True) tensor([0.6102], requires_grad=True)
tensor([1.5142], requires_grad=True) tensor([0.6288], requires_grad=True)
tensor([1.5546], requires_grad=True) tensor([0.6425], requires_grad=True)
tensor([1.5863], requires_grad=True) tensor([0.6524], requires_grad=True)
tensor([1.6114], requires_grad=True) tensor([0.6594], requires_grad=True)
tensor([1.6312], requires_grad=True) tensor([0

tensor([1.8775], requires_grad=True) tensor([0.2785], requires_grad=True)
tensor([1.8781], requires_grad=True) tensor([0.2771], requires_grad=True)
tensor([1.8787], requires_grad=True) tensor([0.2758], requires_grad=True)
tensor([1.8793], requires_grad=True) tensor([0.2745], requires_grad=True)
tensor([1.8798], requires_grad=True) tensor([0.2731], requires_grad=True)
tensor([1.8804], requires_grad=True) tensor([0.2718], requires_grad=True)
tensor([1.8810], requires_grad=True) tensor([0.2705], requires_grad=True)
tensor([1.8816], requires_grad=True) tensor([0.2692], requires_grad=True)
tensor([1.8821], requires_grad=True) tensor([0.2679], requires_grad=True)
tensor([1.8827], requires_grad=True) tensor([0.2666], requires_grad=True)
tensor([1.8833], requires_grad=True) tensor([0.2654], requires_grad=True)
tensor([1.8838], requires_grad=True) tensor([0.2641], requires_grad=True)
tensor([1.8844], requires_grad=True) tensor([0.2628], requires_grad=True)
tensor([1.8849], requires_grad=True) t

tensor([1.9498], requires_grad=True) tensor([0.1142], requires_grad=True)
tensor([1.9500], requires_grad=True) tensor([0.1136], requires_grad=True)
tensor([1.9503], requires_grad=True) tensor([0.1131], requires_grad=True)
tensor([1.9505], requires_grad=True) tensor([0.1125], requires_grad=True)
tensor([1.9507], requires_grad=True) tensor([0.1120], requires_grad=True)
tensor([1.9510], requires_grad=True) tensor([0.1114], requires_grad=True)
tensor([1.9512], requires_grad=True) tensor([0.1109], requires_grad=True)
tensor([1.9514], requires_grad=True) tensor([0.1104], requires_grad=True)
tensor([1.9517], requires_grad=True) tensor([0.1098], requires_grad=True)
tensor([1.9519], requires_grad=True) tensor([0.1093], requires_grad=True)
tensor([1.9521], requires_grad=True) tensor([0.1088], requires_grad=True)
tensor([1.9524], requires_grad=True) tensor([0.1083], requires_grad=True)
tensor([1.9526], requires_grad=True) tensor([0.1078], requires_grad=True)
tensor([1.9528], requires_grad=True) t

tensor([1.9765], requires_grad=True) tensor([0.0533], requires_grad=True)
tensor([1.9767], requires_grad=True) tensor([0.0531], requires_grad=True)
tensor([1.9768], requires_grad=True) tensor([0.0528], requires_grad=True)
tensor([1.9769], requires_grad=True) tensor([0.0525], requires_grad=True)
tensor([1.9770], requires_grad=True) tensor([0.0523], requires_grad=True)
tensor([1.9771], requires_grad=True) tensor([0.0520], requires_grad=True)
tensor([1.9772], requires_grad=True) tensor([0.0518], requires_grad=True)
tensor([1.9773], requires_grad=True) tensor([0.0515], requires_grad=True)
tensor([1.9774], requires_grad=True) tensor([0.0513], requires_grad=True)
tensor([1.9775], requires_grad=True) tensor([0.0511], requires_grad=True)
tensor([1.9777], requires_grad=True) tensor([0.0508], requires_grad=True)
tensor([1.9778], requires_grad=True) tensor([0.0506], requires_grad=True)
tensor([1.9779], requires_grad=True) tensor([0.0503], requires_grad=True)
tensor([1.9780], requires_grad=True) t

tensor([1.9866], requires_grad=True) tensor([0.0305], requires_grad=True)
tensor([1.9867], requires_grad=True) tensor([0.0303], requires_grad=True)
tensor([1.9867], requires_grad=True) tensor([0.0302], requires_grad=True)
tensor([1.9868], requires_grad=True) tensor([0.0300], requires_grad=True)
tensor([1.9868], requires_grad=True) tensor([0.0299], requires_grad=True)
tensor([1.9869], requires_grad=True) tensor([0.0298], requires_grad=True)
tensor([1.9870], requires_grad=True) tensor([0.0296], requires_grad=True)
tensor([1.9870], requires_grad=True) tensor([0.0295], requires_grad=True)
tensor([1.9871], requires_grad=True) tensor([0.0293], requires_grad=True)
tensor([1.9872], requires_grad=True) tensor([0.0292], requires_grad=True)
tensor([1.9872], requires_grad=True) tensor([0.0290], requires_grad=True)
tensor([1.9873], requires_grad=True) tensor([0.0289], requires_grad=True)
tensor([1.9873], requires_grad=True) tensor([0.0288], requires_grad=True)
tensor([1.9874], requires_grad=True) t

tensor([1.9946], requires_grad=True) tensor([0.0124], requires_grad=True)
tensor([1.9946], requires_grad=True) tensor([0.0123], requires_grad=True)
tensor([1.9946], requires_grad=True) tensor([0.0123], requires_grad=True)
tensor([1.9946], requires_grad=True) tensor([0.0122], requires_grad=True)
tensor([1.9947], requires_grad=True) tensor([0.0121], requires_grad=True)
tensor([1.9947], requires_grad=True) tensor([0.0121], requires_grad=True)
tensor([1.9947], requires_grad=True) tensor([0.0120], requires_grad=True)
tensor([1.9947], requires_grad=True) tensor([0.0120], requires_grad=True)
tensor([1.9948], requires_grad=True) tensor([0.0119], requires_grad=True)
tensor([1.9948], requires_grad=True) tensor([0.0119], requires_grad=True)
tensor([1.9948], requires_grad=True) tensor([0.0118], requires_grad=True)
tensor([1.9948], requires_grad=True) tensor([0.0117], requires_grad=True)
tensor([1.9949], requires_grad=True) tensor([0.0117], requires_grad=True)
tensor([1.9949], requires_grad=True) t

tensor([1.9978], requires_grad=True) tensor([0.0049], requires_grad=True)
tensor([1.9979], requires_grad=True) tensor([0.0049], requires_grad=True)
tensor([1.9979], requires_grad=True) tensor([0.0049], requires_grad=True)
tensor([1.9979], requires_grad=True) tensor([0.0048], requires_grad=True)
tensor([1.9979], requires_grad=True) tensor([0.0048], requires_grad=True)
tensor([1.9979], requires_grad=True) tensor([0.0048], requires_grad=True)
tensor([1.9979], requires_grad=True) tensor([0.0048], requires_grad=True)
tensor([1.9979], requires_grad=True) tensor([0.0047], requires_grad=True)
tensor([1.9979], requires_grad=True) tensor([0.0047], requires_grad=True)
tensor([1.9979], requires_grad=True) tensor([0.0047], requires_grad=True)
tensor([1.9979], requires_grad=True) tensor([0.0047], requires_grad=True)
tensor([1.9980], requires_grad=True) tensor([0.0047], requires_grad=True)
tensor([1.9980], requires_grad=True) tensor([0.0046], requires_grad=True)
tensor([1.9980], requires_grad=True) t

tensor([1.9991], requires_grad=True) tensor([0.0020], requires_grad=True)
tensor([1.9991], requires_grad=True) tensor([0.0020], requires_grad=True)
tensor([1.9991], requires_grad=True) tensor([0.0020], requires_grad=True)
tensor([1.9991], requires_grad=True) tensor([0.0020], requires_grad=True)
tensor([1.9991], requires_grad=True) tensor([0.0020], requires_grad=True)
tensor([1.9991], requires_grad=True) tensor([0.0020], requires_grad=True)
tensor([1.9991], requires_grad=True) tensor([0.0020], requires_grad=True)
tensor([1.9991], requires_grad=True) tensor([0.0020], requires_grad=True)
tensor([1.9991], requires_grad=True) tensor([0.0020], requires_grad=True)
tensor([1.9991], requires_grad=True) tensor([0.0019], requires_grad=True)
tensor([1.9991], requires_grad=True) tensor([0.0019], requires_grad=True)
tensor([1.9992], requires_grad=True) tensor([0.0019], requires_grad=True)
tensor([1.9992], requires_grad=True) tensor([0.0019], requires_grad=True)
tensor([1.9992], requires_grad=True) t

tensor([1.9996], requires_grad=True) tensor([0.0009], requires_grad=True)
tensor([1.9996], requires_grad=True) tensor([0.0009], requires_grad=True)
tensor([1.9996], requires_grad=True) tensor([0.0009], requires_grad=True)
tensor([1.9996], requires_grad=True) tensor([0.0009], requires_grad=True)
tensor([1.9996], requires_grad=True) tensor([0.0009], requires_grad=True)
tensor([1.9996], requires_grad=True) tensor([0.0009], requires_grad=True)
tensor([1.9996], requires_grad=True) tensor([0.0009], requires_grad=True)
tensor([1.9996], requires_grad=True) tensor([0.0009], requires_grad=True)
tensor([1.9996], requires_grad=True) tensor([0.0009], requires_grad=True)
tensor([1.9996], requires_grad=True) tensor([0.0009], requires_grad=True)
tensor([1.9996], requires_grad=True) tensor([0.0009], requires_grad=True)
tensor([1.9996], requires_grad=True) tensor([0.0009], requires_grad=True)
tensor([1.9996], requires_grad=True) tensor([0.0009], requires_grad=True)
tensor([1.9996], requires_grad=True) t

- optim은 최적화를 간편하게 해주는 모델

- 그 중 SGD는 확률적 경사하강법이라는 것으로, optim의 한 기법

- optimizer.zero_grad()는 텐서들의 미분값을 초기화 해주는 것


zero_grad()로 gradient 초기화, backward()로 계산, step()으로 개선

train 값에 대해서 hypothesis를 예측하고, 차이가 얼만큼 나는지에 대해서 Cost를 계산한 뒤에 Optimizer로 이를 학습하는 과정의 반복





- 실제로 학습시켜 보았더니 W는 2에 가까워지고 b는 0에 가까워지는것을 확인