<a href="https://colab.research.google.com/github/Hongyongmin/Edwith-Pytorch/blob/main/5_Logistic_Regression_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [ ]:
torch.manual_seed(1)

In [ ]:
x_data = [[1,2],[2,3],[3,1],[4,3],[5,3],[6,2]]
y_data = [[0],[0],[0],[1],[1],[1]]

In [ ]:
x_train = torch.FloatTensor(x_data)
y_train = torch.FloatTensor(y_data)

In [ ]:
print(x_train.shape)
print(y_train.shape)

torch.Size([6, 2])
torch.Size([6, 1])


In [ ]:
print('e^1 equals: ', torch.exp(torch.FloatTensor([1]))) ##exp 함수로 e를 계산할 수 있음

e^1 equals:  tensor([2.7183])


In [ ]:
W = torch.zeros((2,1), requires_grad=True)
b = torch.zeros(1,requires_grad=True)

In [ ]:
hypothesis = 1 / (1 + torch.exp(-(x_train.matmul(W) + b))) ##로지스틱회귀의 정의

In [ ]:
print(hypothesis)              # 최초의 hypothesis를 0으로 둬서 기본값인 0.5로 나옴
print(hypothesis.shape)  

tensor([[0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000]], grad_fn=<MulBackward0>)
torch.Size([6, 1])


In [ ]:
print('1/(1+e^{-1}) equals: ', torch.sigmoid(torch.FloatTensor([1])))

1/(1+e^{-1}) equals:  tensor([0.7311])


In [ ]:
hypothesis = torch.sigmoid(x_train.matmul(W) + b) ##sigmoid로 로지스틱회귀를 대체할 수 있음

In [ ]:
print(hypothesis)
print(hypothesis.shape)

tensor([[0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000]], grad_fn=<SigmoidBackward>)
torch.Size([6, 1])


In [ ]:
print(hypothesis)
print(y_train)

tensor([[0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000]], grad_fn=<SigmoidBackward>)
tensor([[0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.]])


In [ ]:
-(y_train[0] * torch.log(hypothesis[0]) +       
 (1 - y_train[0]) * torch.log(1 - hypothesis[0]))    #첫 Element를 가지고 계산한 손실값

tensor([0.6931], grad_fn=<NegBackward>)

In [ ]:
losses = -(y_train * torch.log(hypothesis) +
          (1 - y_train) * torch.log(1 - hypothesis))
print(losses)                                      #손실값의 정의

tensor([[0.6931],
        [0.6931],
        [0.6931],
        [0.6931],
        [0.6931],
        [0.6931]], grad_fn=<NegBackward>)


In [ ]:
cost = losses.mean()
print(cost)

tensor(0.6931, grad_fn=<MeanBackward0>)


In [ ]:
F.binary_cross_entropy(hypothesis, y_train)       # 이 함수를 이용하여 수식없이 계산가능함

tensor(0.6931, grad_fn=<BinaryCrossEntropyBackward>)

In [ ]:
W = torch.zeros((2,1), requires_grad=True)
b = torch.zeros(1, requires_grad=True)

optimizer = optim.SGD([W,b], lr=1)

nb_epochs = 1000
for epoch in range(nb_epochs + 1):
    
    hypothesis = torch.sigmoid(x_train.matmul(W) +b)
    cost = F.binary_cross_entropy(hypothesis, y_train)
    
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    if epoch % 100 == 0:
        print('Epoch {:4d}/{} Cost: {:.6f}'.format(
            epoch, nb_epochs, cost.item()
        ), W)

Epoch    0/1000 Cost: 0.693147 tensor([[0.7500],
        [0.1667]], requires_grad=True)
Epoch  100/1000 Cost: 0.134722 tensor([[1.5568],
        [0.3875]], requires_grad=True)
Epoch  200/1000 Cost: 0.080643 tensor([[1.9606],
        [0.7348]], requires_grad=True)
Epoch  300/1000 Cost: 0.057900 tensor([[2.2485],
        [0.9331]], requires_grad=True)
Epoch  400/1000 Cost: 0.045300 tensor([[2.4706],
        [1.0731]], requires_grad=True)
Epoch  500/1000 Cost: 0.037261 tensor([[2.6517],
        [1.1815]], requires_grad=True)
Epoch  600/1000 Cost: 0.031673 tensor([[2.8046],
        [1.2699]], requires_grad=True)
Epoch  700/1000 Cost: 0.027556 tensor([[2.9371],
        [1.3447]], requires_grad=True)
Epoch  800/1000 Cost: 0.024394 tensor([[3.0539],
        [1.4095]], requires_grad=True)
Epoch  900/1000 Cost: 0.021888 tensor([[3.1584],
        [1.4667]], requires_grad=True)
Epoch 1000/1000 Cost: 0.019852 tensor([[3.2530],
        [1.5179]], requires_grad=True)


In [ ]:
print(x_train)
print(W)
print(b)
print(cost)

tensor([[1., 2.],
        [2., 3.],
        [3., 1.],
        [4., 3.],
        [5., 3.],
        [6., 2.]])
tensor([[3.2530],
        [1.5179]], requires_grad=True)
tensor([-14.4819], requires_grad=True)
tensor(0.0199, grad_fn=<BinaryCrossEntropyBackward>)


In [ ]:
hypothesis = torch.sigmoid(x_train.matmul(W)+b)
print(hypothesis[:5])

SyntaxError: ignored

In [ ]:
prediction = hypothesis >= torch.FloatTensor([0.5])
print(prediction[:5])

tensor([[False],
        [False],
        [False],
        [ True],
        [ True]])


In [ ]:
print(prediction[:5])
print(y_train[:5])

tensor([[False],
        [False],
        [False],
        [ True],
        [ True]])
tensor([[0.],
        [0.],
        [0.],
        [1.],
        [1.]])


In [ ]:
correct_prediction = prediction.float() == y_train
print(correct_prediction[:5])

tensor([[True],
        [True],
        [True],
        [True],
        [True]])


In [ ]:
class BinaryClassifier(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(2,1)
        self.sigmoid = nn.Sigmoid()
        
    def forward(self,x):
        return self.sigmoid(self.linear(x))

In [ ]:
model = BinaryClassifier()

In [ ]:
optimizer = optim.SGD(model.parameters(), lr=1)

nb_epochs = 100
for epoch in range(nb_epochs + 1):
    
    hypothesis = model(x_train)
    
    cost = F.binary_cross_entropy(hypothesis, y_train)
    
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    if epoch % 10 ==0:
        prediction = hypothesis >= torch.FloatTensor([0.5])
        correct_prediction = prediction.float() == y_train
        accuracy = correct_prediction.sum().item() / len(correct_prediction)
        print('Epoch {:4d}/{} Cost: {:.6f} Accuracy {:2.2f}'.format(
            epoch, nb_epochs, cost.item(), accuracy * 100
        ))
       
        
print(W)
print(b)

Epoch    0/100 Cost: 0.036081 Accuracy 100.00
Epoch   10/100 Cost: 0.035474 Accuracy 100.00
Epoch   20/100 Cost: 0.034888 Accuracy 100.00
Epoch   30/100 Cost: 0.034321 Accuracy 100.00
Epoch   40/100 Cost: 0.033772 Accuracy 100.00
Epoch   50/100 Cost: 0.033241 Accuracy 100.00
Epoch   60/100 Cost: 0.032726 Accuracy 100.00
Epoch   70/100 Cost: 0.032228 Accuracy 100.00
Epoch   80/100 Cost: 0.031744 Accuracy 100.00
Epoch   90/100 Cost: 0.031275 Accuracy 100.00
Epoch  100/100 Cost: 0.030820 Accuracy 100.00
tensor([[3.2530],
        [1.5179]], requires_grad=True)
tensor([-14.4819], requires_grad=True)


## 